### ISSUE TITLE
The arrows, on mouseover is show and on mouseout is hide

### ISSUE THREAD

**Issue by chenxiaochun** [akiran/react-slick#1032]
I have implemented this effect with css.

```css
.box{
  :global{
    .slick-prev, .slick-next{
      z-index: 1;
      opacity: 0;
      transition: .5s all;
    }
    .slick-prev{
      left: -30px;
    }
    .slick-next{
      right: -10px;
    }
    .slick-prev:before, .slick-next:before{
      color: #4C96FF;
      font-size: 30px;
    }
  }
  &:hover{
    :global{
      .slick-prev, .slick-next{
        opacity: 1;
      }
    }
  }
}
```

But, do you think about adding such a parameter? Thanks very much.
