### ISSUE TITLE
Display one item and half of the prev/next ones

### ISSUE THREAD

**Issue by duclh-2011** [akiran/react-slick#2203]
I'm trying to create an interface like the one shown below:

![image](https://user-images.githubusercontent.com/54925990/208486478-a42a9b55-32ad-4edc-92c1-db8230f15bb6.png)

I tried many ways, but it doesn't work! 
So, i find in internet, and see this [issue](https://github.com/kenwheeler/slick/issues/1784) 

It say : 

```css
.slick-list .slick-track{
padding-left: 12.5%;
}
```

I tried that way, but it doesn't work. Can anyone help me?
