### ISSUE TITLE
How can I add linear-gradient on slick-track level?

### ISSUE THREAD

**Issue by fzn0x** [akiran/react-slick#2342]
Hi @akiran thanks for maintaining this amazing open source, I would like to ask you or other contributors, how can I add linear-gradient on slick-track level?

I'm using the slider to capture the expected result below:

![Screenshot 2024-02-07 174457](https://github.com/akiran/react-slick/assets/50759463/c7c5b263-c386-4f92-a186-543ff3618deb)

Instead on slider level, i want the linear-gradient above the slider, from what I inspect, it is the `slide-track` element that was above the slides, I already modify the slick-track CSS but somehow it messed up other styles.

Thanks!

**Comment by fzn0x** [comment]
Solved by adding `pointer-events: none;`

```css
.SliderViewPortGradient {
  width: 100%;
  aspect-ratio: 9/3;
  height: 100%;
  background: linear-gradient(90deg, rgba(0, 0, 0, 0.9) 0%, rgba(0, 0, 0, 0) 30%, rgba(0, 0, 0, 0) 50%, rgba(0, 0, 0, 0) 30%, rgba(0, 0, 0, 0.9) 100%);
  position: absolute;
  z-index: 100;
  pointer-events: none; /* Add this line to allow pointer events to pass through */
}
```
