### ISSUE TITLE
Issue with stacking slides before react-slick is initialized…

### ISSUE THREAD

**Issue by chemoish** [akiran/react-slick#254]
https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L80

`slick-initialized` is hard coded and not set by any events.

![screen shot 2016-03-03 at 8 14 59 pm](https://cloud.githubusercontent.com/assets/549319/13517870/a648dcee-e17c-11e5-88e8-c524eb1e9551.png)

How can you prevent stacking slides? Thoughts?

_In kenwheeler/slick, `slick-initialized` is an event… so you can prevent FOUC._

**Comment by akiran** [comment]
Render slick slider only when you need.
slick-initialized won't be necessary in react

**Comment by chemoish** [comment]
I need it immediately? or am I missing something?

I solved this the FOUC issue by…

```jsx
componentDidUpdate() {
    this._slider_container.classList.add('initialized');
}

render() {
    return (
        <div className="slider-container" ref={c => (this._slider_container = c)}>...</div>
    );
}
```

```css
// styles

.slider-container
{
    display: none;

    .initialized &
    {
        display: block;
    }
}
```
