### ISSUE TITLE
Fade with Links components only shows the last Link

### ISSUE THREAD

**Issue by Artemidas** [akiran/react-slick#269]
It fades correctly and the content is changing, but if there is a Link in each slide, only the last Link will be clicked.
Here I modified jsfiddle to show an example https://jsfiddle.net/20bumb4g/166/

**Comment by josyan** [comment]
Same problem. It looks like the hidden slides have an opacity of 0, but are still displayed (`display: block;`), so interaction is only possible with the last slide which is on top.

**Comment by josyan** [comment]
I solved my problem by adding

```css
.slick-initialized .slick-slide.slick-active {
  z-index: 1;
}
```

in my css.
