### ISSUE TITLE
Hook for re-layout

### ISSUE THREAD

**Issue by mhuebert** [akiran/react-slick#27]
The CSS for .slick-slide specifies a height of 100%, which causes images in my slides to be stretched out of proportion, depending how the browser window is sized. If I take off the height property, it works fine sometimes, but often re-renders at a 1px height. If there was a way for me to tell the component to re-calculate its size, I would first of all use this to calculate the size after the initial image had loaded (using onLoad), and then also re-calculate the size as the user resizes their browser window.

**Comment by jdsharp** [comment]
I hacked this by using the `className` setting and putting in an arbitrary class (such as 'foobar-1', if neeeded you can have it increment/change foobar-1 to foobar-2, etc.)

**Comment by grrowl** [comment]
I hacked this with a static height and setting size of the slides by using viewport-width units:

```css
.slick-slider {
    @include reset(ul);

    /* almost fill the viewport */
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 80px;
    white-space: nowrap; /* inline elements will go on forever */
    overflow: hidden;
}
.slick-slide {
      position: relative; /* position things inside */
      display: inline-block; /* act as an inline element */
      height: 100%; /* take up whole height of slider parent */
      width: 100vw !important; /* be as wide as the viewport */
}
```

You can also lean on the `onChange` callback to recalc position if you need (and set via className or setState)
