### ISSUE TITLE
How to force the slides to have fixed height without breaking centering and navigation?

### ISSUE THREAD

**Issue by michalczaplinski** [akiran/react-slick#732]
I can see that in every example, the width of the elements with `.slick-track` and `.slick-slider` changes as the user resizes the window, which then affects the height of the carousel.

What I would like is to be able to fix the height of the carousel in such a way that the slides do not resize as I resize the browser window. Think: iTunes Store carousel.

What I have tried:

Setting:
```css
.slick-slide { width: 500px !important; }
```
and in the  carousel settings:
```jsx
<Slider
  adaptiveHeight={false}
  variableWidth={false}
  centerPadding={0}
  autoplay
  centerMode
  slidesToShow={3}
  slidesToScroll={1}
  swipe
  draggable={false}
  infinite
>
```

This achieves the desired effect, but causes the carousel layout and navigation to break (the arrow click moves the carousel by less than the whole image and the middle slide is not centered anymore:

![kapture 2017-04-27 at 12 38 43](https://cloud.githubusercontent.com/assets/5417266/25479806/79fe70bc-2b46-11e7-8a3c-d8281b00e84e.gif)

**Comment by vijayst** [comment]
i have the same problem!

**Comment by jsamr** [comment]
@vijayst @michalczaplinski try this:

```css
  .slick-slide {
    height: auto; // ← that must not be ignored
  }
  .slick-track {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: stretch;
  }
```

**Comment by yenly** [comment]
Didn't the original slick library recommend using variableWidth: true?

http://kenwheeler.github.io/slick/

**Comment by laveesingh** [comment]
This doesn't seem to be a problem with react-slick library. You can take a look at varaibleWidth prop if that can help in some way. Please feel free to request reopen if disagree.

**Comment by shermdevc** [comment]
> @vijayst @michalczaplinski try this:
> 
> ```css
>   .slick-slide {
>     height: auto; // ← that must not be ignored
>   }
>   .slick-track {
>     display: flex;
>     flex-direction: row;
>     flex-wrap: nowrap;
>     align-items: stretch;
>   }
> ```

really helped me , Thanks dear

**Comment by Quad-Plex** [comment]
> ```css
>   .slick-slide {
>     height: auto; // ← that must not be ignored
>   }
> ```

I had a somewhat unrelated issue where slick would continually add to the height of my individual slick-slides when they were moved, extending them downwards, `height: auto !important` ended up being the fix I needed, thanks a lot!

**Comment by badeed** [comment]
```css
.slick-slide {
  height: auto !important;
}

.slick-track {
  display: flex !important;
  flex-direction: row !important;
  flex-wrap: nowrap !important;
  align-items: stretch !important;
}

.slick-slide > div {
/*
Card CSS goes here
*/
}
```
There was one step missing for me. Since there is a `<div>` element for each slide in the slider(could be just a me issue) i had to edit the direct div child as my Card body for it to work finally.

 i am not quite sure if i needed all the !impotant but i was fed up with testing and trying.
