### ISSUE TITLE
Easy way to change arrow color ? Not the background color

### ISSUE THREAD

**Issue by foodaka** [akiran/react-slick#790]
I want to change the inner arrow color. In the demo the browser has the css as
```
font-size: 20px;
    line-height: 1;
    color: #00558B;
    opacity: .75;
```

how do i replicate this? Is there an easy way to change this color property? I have no issue with custom arrow changing background, but i only want to change arrow color.

https://jsfiddle.net/9raxke45/

Cheers!

**Comment by radiovisual** [comment]
Just target the button's contents directly like this:

```css
.slick-prev:before,
.slick-next:before {
  color: yellow;
}
```

https://jsfiddle.net/ss6LedtL/
